name: Build and deploy full-stack Node.js app to Azure Web App - lab13-webapp-aziz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      # Install root devDependencies (like concurrently)
      - name: Install root devDependencies
        run: npm install

      # Install server dependencies
      - name: Install server dependencies
        run: npm install --prefix server

      # Install client dependencies
      - name: Install client dependencies
        run: npm install --prefix client

      # Build React frontend
      - name: Build React frontend
        run: npm run build --prefix client

      # Upload fullstack artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB04DF63FC4C49E985C6C87B7F01ABF3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2666A1E95BB44CD9DF1AD8BF56E18B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_404D7DCA1BE04680B8DC4931E4126FB1 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lab13-webapp-aziz'
          slot-name: 'Production'
          package: .
